sudo: false
language: python
dist: trusty
matrix:
  include:
    # lint
    - python: "3.5"
      env: TOX_POSARGS="-e lint"
    # core
    - python: "3.5"
      env: TOX_POSARGS="-e py35-rlp0"
    - python: "3.5"
      env: TOX_POSARGS="-e py35-rlp1"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-rlp0"
    - python: "3.6"
      env: TOX_POSARGS="-e py36-rlp1"
    - python: "3.7"
      env: TOX_POSARGS="-e py37-rlp0"
    - python: "3.7"
      env: TOX_POSARGS="-e py37-rlp1"
    - python: "pypy3.5"
      env: TOX_POSARGS="-e pypy3-rlp0"
    - python: "pypy3.5"
      env: TOX_POSARGS="-e pypy3-rlp1"
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
before_script:
  - pip freeze
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
