sudo: false
language: python
dist: trusty
matrix:
  include:
    # lint
    - python: "3.5"
      env: TOX_POSARGS="-e flake8"
    # core
    - python: "3.5"
      env: TOX_POSARGS="-e py35"
    - python: "3.6"
      env: TOX_POSARGS="-e py36"
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
before_script:
  - pip freeze
script:
  - tox $TOX_POSARGS
after_script:
  - cat .tox/$TOX_POSARGS/log/*.log
